name: flutter_posts_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  internet_connection_checker_plus: ^2.5.1
  shared_preferences:
  bloc: ^9.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.0
  google_fonts: ^6.3.2
  provider:
  flutter_bloc:
  dio:
  equatable:
  cupertino_icons: ^1.0.8
  get_it:
  intl: ^0.20.2
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
